"""
IX-Operator package bootstrap.
"""

from __future__ import annotations

from ix_operator.agents import (
    AgentDefinition,
    AgentMemoryStore,
    AgentMessage,
    AgentRegistry,
    AgentRuntimeState,
    AgentStatus,
    MemoryValue,
)
from ix_operator.audit import AuditCategory, AuditEvent, AuditLogger, AuditSeverity
from ix_operator.bus import AgentBus, ChannelBinding, ReceivedAgentMessage
from ix_operator.config import OperatorConfig, OperatorMode, RuntimePaths, TransportBackend
from ix_operator.ix import (
    AgentBlock,
    ExecutionReport,
    GoalStatement,
    IxInterpreter,
    IxParseError,
    IxProgram,
    IxStatement,
    RememberStatement,
    SayEmission,
    SayStatement,
    parse_ix_script,
)
from ix_operator.runtime import RuntimeContext
from ix_operator.session import (
    CHALLENGE_LEN,
    DEFAULT_SESSION_TTL_SECONDS,
    HandshakeAck,
    HandshakeCoordinator,
    HandshakeCryptoBackend,
    HandshakeHello,
    HandshakeResponse,
    HandshakeTranscript,
    LocalSecrets,
    MAX_SESSIONS_DEFAULT,
    PROTOCOL_LABEL,
    PeerIdentity,
    SIGNATURE_LEN,
    SessionManager,
    SessionMaterial,
    SessionRecord,
    SessionRole,
    SessionState,
)
from ix_operator.transport import (
    DEFAULT_MESSAGE_REGISTRY_SIZE,
    DEFAULT_PACKET_SIZE,
    DEFAULT_RECEIVE_TIMEOUT_SECONDS,
    DEFAULT_REPLAY_WINDOW_SIZE,
    HEADER_SIZE,
    MAX_PACKET_SIZE,
    MAX_SEQUENCE_NUMBER,
    MESSAGE_ID_SIZE,
    MIN_PACKET_SIZE,
    NONCE_SIZE,
    PROTOCOL_VERSION,
    PacketCodec,
    SESSION_ID_FIELD_SIZE,
    TransportCryptoBackend,
    LocalDelivery,
    LocalTransportClosedError,
    LocalTransportEndpoint,
    LocalTransportHub,
    MessageRegistry,
    MessageType,
    Packet,
    PacketHeader,
    ReplayRejectedError,
    ReplayWindow,
    SessionBindingError,
    TransportSessionState,
    build_packet,
    packet_fingerprint,
)

__all__ = [
    "__version__",
    "PRODUCT_NAME",
    "AgentBlock",
    "AgentBus",
    "AgentDefinition",
    "AgentMemoryStore",
    "AgentMessage",
    "AgentRegistry",
    "AgentRuntimeState",
    "AgentStatus",
    "AuditCategory",
    "AuditEvent",
    "AuditLogger",
    "AuditSeverity",
    "CHALLENGE_LEN",
    "ChannelBinding",
    "DEFAULT_MESSAGE_REGISTRY_SIZE",
    "DEFAULT_PACKET_SIZE",
    "DEFAULT_RECEIVE_TIMEOUT_SECONDS",
    "DEFAULT_REPLAY_WINDOW_SIZE",
    "DEFAULT_SESSION_TTL_SECONDS",
    "ExecutionReport",
    "GoalStatement",
    "HEADER_SIZE",
    "HandshakeAck",
    "HandshakeCoordinator",
    "HandshakeCryptoBackend",
    "HandshakeHello",
    "HandshakeResponse",
    "HandshakeTranscript",
    "IxInterpreter",
    "IxParseError",
    "IxProgram",
    "IxStatement",
    "LocalDelivery",
    "LocalSecrets",
    "LocalTransportClosedError",
    "LocalTransportEndpoint",
    "LocalTransportHub",
    "MAX_PACKET_SIZE",
    "MAX_SEQUENCE_NUMBER",
    "MAX_SESSIONS_DEFAULT",
    "MESSAGE_ID_SIZE",
    "MIN_PACKET_SIZE",
    "MemoryValue",
    "NONCE_SIZE",
    "OperatorConfig",
    "OperatorMode",
    "PROTOCOL_LABEL",
    "PROTOCOL_VERSION",
    "Packet",
    "PacketCodec",
    "PacketHeader",
    "PeerIdentity",
    "ReceivedAgentMessage",
    "RememberStatement",
    "ReplayRejectedError",
    "ReplayWindow",
    "RuntimeContext",
    "RuntimePaths",
    "SESSION_ID_FIELD_SIZE",
    "SIGNATURE_LEN",
    "SayEmission",
    "SayStatement",
    "SessionBindingError",
    "SessionManager",
    "SessionMaterial",
    "SessionRecord",
    "SessionRole",
    "SessionState",
    "TransportBackend",
    "TransportCryptoBackend",
    "TransportSessionState",
    "MessageRegistry",
    "MessageType",
    "build_packet",
    "packet_fingerprint",
    "parse_ix_script",
]

PRODUCT_NAME = "IX-Operator"
__version__ = "0.1.0"
